### ISSUE TITLE
[sponsor] add Puppet-BR community sponsor 

### ISSUE THREAD

**Issue by adrianovieira** [adrianovieira/devopsdays-web#3]
Add logo of Puppet-BR community sponsor

**Comment by gutocarvalho** [comment]
![puppet-br](https://cloud.githubusercontent.com/assets/663841/17703665/e8c4a7c0-63a8-11e6-976d-86b710a7921b.jpg)

**Comment by gutocarvalho** [comment]
http://telegram.me/puppetbr

**Comment by adrianovieira** [comment]
resolvido
