### ISSUE TITLE
[sponsor] add Docker-BR community sponsor

### ISSUE THREAD

**Issue by adrianovieira** [adrianovieira/devopsdays-web#4]
Add logo of Docker-BR community sponsor

**Comment by gutocarvalho** [comment]
![docker-br](https://cloud.githubusercontent.com/assets/663841/17703650/d4778404-63a8-11e6-8c9c-c73cbd7b75e5.png)

**Comment by gutocarvalho** [comment]
http://telegram.me/dockerbr

**Comment by adrianovieira** [comment]
resolvido
