### ISSUE TITLE
[sponsor] add DevOps-BR community Sponsor

### ISSUE THREAD

**Issue by gutocarvalho** [adrianovieira/devopsdays-web#5]
Add logo of DevOps-BR community sponsor

**Comment by gutocarvalho** [comment]
http://telegram.me/devopsbr

**Comment by gutocarvalho** [comment]
![image](https://cloud.githubusercontent.com/assets/663841/17704025/0afa5d52-63aa-11e6-9535-db7cd038abff.png)

**Comment by adrianovieira** [comment]
resolvido
